username:
password:
phone_number:

profile_path: "" #can be empty, will default to 'C:\Users\<user>\AppData\Local\Google\Chrome\User Data\Default'

positions:
  -

locations:
  -
  # - Remote

salary:
rate:
# --------- Optional Parameters -------
uploads:
  Resume: # PATH TO resume

  #Cover Letter: \ PATH TO cover letter
  #Photo: # PATH TO photo

output_filename:
  -  # Default is 'output.txt'

blacklist:
  -

experience_level:
  # - 1 # Entry level
  # - 2 # Associate
  # - 3 # Mid-Senior level
  # - 4 # Director
  # - 5 # Executive
  # - 6 # Internship

# Auto-answer for common yes/no questions (use True/False)
auto_answer_questions:
  requireVisa: False
  legallyAuthorized: True
  urgentFill: True
  commute: True
  backgroundCheck: True
  degreeCompleted:
    -

languages:
  english: Native or bilingual
  chinese: None # Add other languages as needed

industry_experience:
  Sales: 0
  Business Development: 0
  Business Travel: 0
  default: 0 # For unspecified industries
